version: "3.8"

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      #RabbitMq instance
      - 5672:5672
      #Web interface
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dapr-network

  formulaairline:
    build:
      context: .
      dockerfile: FormulaAirline/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
      - placement
    networks:
      - dapr-network

  formulaairline-dapr:
    image: "daprio/daprd:1.14.4"
    command:
      [
        "./daprd",
        "--app-id",
        "FormulaAirline",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006",
        "--resources-path",
        "/Components",
      ]
    volumes:
      - "./Components:/Components"
    depends_on:
      - formulaairline
      - rabbitmq
      - placement
    network_mode: "service:formulaairline"

  receiverwebapi:
    build:
      context: .
      dockerfile: ReceiverWebAPI/Dockerfile
    ports:
      - "7005:7005"
    depends_on:
      - rabbitmq
      - placement
    networks:
      - dapr-network

  receiverwebapi-dapr:
    image: "daprio/daprd:1.14.4"
    command:
      [
        "./daprd",
        "--app-id",
        "ReceiverWebAPI",
        "--app-port",
        "7005",
        "--placement-host-address",
        "placement:50006",
        "--resources-path",
        "/Components",
      ]
    volumes:
      - "./Components:/Components"
    depends_on:
      - receiverwebapi
      - rabbitmq
      - placement
    network_mode: "service:receiverwebapi"

  placement:
    image: "daprio/dapr:1.14.4"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
